### ISSUE TITLE
How to close the 'VLC Video Output' pop-up window?

### ISSUE THREAD

**Issue by fergus1987** [Varcus-Solutions/VlcMedia-ue5-vlc4#1]
First of All, Thank u for your work!
Here is my problem. When some video stream is captured and displayed in program, whatever in Editor or Packeted exe, there will be a pop-up window named 'VLC Video Output'. How to forbid it?

**Comment by swainsoftware** [comment]
Hey, this code is still WIP, my friend.
Did you update /ThirdParty/vlc/Win64/ libraries to newer versions? I can reproduce the issue you describe in case newer dlls are in use, so use dlls from the repo. Unfortunately this particular vlc version was compiled in April 2022 and no longer available from neither vlc source nor nightly builds.
Im working on a plugin update for latest vlc, but it takes time.

**Comment by fergus1987** [comment]
Thank u for ur quick replay!
Actually, I run your Plugin on 4.27.2 Chaos with default version of libraries.
So maybe it is just incompatible problem? However, your Plugin is the only Version I can find in github that works well with 4.27.2 Chaos Except the issue I mentioned last time.
Looking forward to your update and appreciating for your works!
